# -*- coding: utf-8 -*-
"""3행(예시행) 값 — KOCARC_.xlsx 3행에서 추출. build_template 이 사용.
사용자 큐레이션 예시 1건(가상 환자). 실제 환자 데이터 아님."""
EXAMPLES = {
    '환자목록': {
        '__KEY__': None,
        '@DT:ER_DATE,ER_CLOCK_HOUR,ER_CLOCK_MIN': '2026-06-15 09:30',
        'PAT_NM': None,
        'SEX': 'Male',
        '@DOB:DOB_YY,DOB_MM,DOB_DD': '1970-05-15',
    },
    '공통영역': {
        '__KEY__': None,
        'NATIONALITY': '한국인',
        'ER_LOCATION': '직접내원',
        'ER_IN_STAT': '심정지상태',
        'ARREST_SIGUNGU': '대도시(구)',
        '@TREE:ER_CPR1|1=ER_CPR1_N;2=ER_CPR1_Y_20': '시행 20분이내 중단 - 소생술중단사망',
        '@TREE:ER_CPR2|2=ER_CPR2_Y': '시행 - Any ROSC없이 사망',
        '@DT:ER_CPR_STOP_DATE,ER_CPR_STOP_HOUR,ER_CPR_STOP_MIN': '2026-06-15 09:30',
        '@DT:ER_ANY_ROSC_DATE,ER_ANY_ROSC_HOUR,ER_ANY_ROSC_MIN': None,
        '@DT:ER_SUS_ROSC_DATE,ER_SUS_ROSC_HOUR,ER_SUS_ROSC_MIN': None,
        '@TREE:ER_CPR_RESULT|1=ER_CPR_RESULT_LIVE;3=ER_CPR_RESULT_DIE': '사망 - 사망',
        '@DT:ER_DIE_DATE,ER_DIE_HOUR,ER_DIE_MIN': '2026-06-15 09:30',
        '@DT:ER_OUT_DATE,ER_OUT_HOUR,ER_OUT_MIN': '2026-06-15 09:30',
        '@DT:HOSP_AD_DATE,HOSP_AD_HOUR,HOSP_AD_MIN': None,
        'HOSP_AD_ROOM': None,
        'HOSP_AD_STAT': None,
        '@TREE:HOSP_RESULT|1=HOSP_RESULT_OUT': None,
        '@DT:HOSP_OUT_DATE,HOSP_OUT_HOUR,HOSP_OUT_MIN': None,
        '@DT:HOSP_DIE_DATE,HOSP_DIE_HOUR,HOSP_DIE_MIN': None,
        'HOSP_CPC': None,
        'FU6M_STAT': None,
        '@DT:FU6M_DIE_DATE,FU6M_DIE_HOUR,FU6M_DIE_MIN': '2026-06-15 09:30',
        'F6M_CPC': 'CPC 1 (뇌기능이 좋음)',
    },
    '예방역학': {
        '__KEY__': None,
        'PRE_ACT': '정상(CPC 1 or 2)',
        '@GROUP:FHX_CA_F,FHX_CA_M,FHX_CA_B,FHX_CA_S,FHX_CA_NO,FHX_CA_UK': '부',
        '@GROUP:FHX_ACS_F,FHX_ACS_M,FHX_ACS_B,FHX_ACS_S,FHX_ACS_NO,FHX_ACS_UK': '부',
        '@GROUP:FHX_CVA_F,FHX_CVA_M,FHX_CVA_B,FHX_CVA_S,FHX_CVA_NO,FHX_CVA_UK': '부',
        '@GROUP:FHX_ARR_F,FHX_ARR_M,FHX_ARR_B,FHX_ARR_S,FHX_ARR_NO,FHX_ARR_UK': '부',
        'SMOKING': '현재흡연',
        '@TREE:ALCOHOL|1=ALCOHOL_DOSE': '있음 - 최근 1년간 없음',
        'HTN': '예',
        'HTNTX': '예',
        '@GROUP:HTNTX1,HTNTX2,HTNTX3': '운동-식이치료',
        'DM': '예',
        'DMTX': '예',
        '@GROUP:DMTX1,DMTX2,DMTX3,DMTX4': '운동-식이치료',
        'DYSLIPID': '예',
        'DYSLTX': '예',
        '@GROUP:DYSLTX1,DYSLTX2,DYSLTX3': '운동-식이치료',
    },
    '지역사회': {
        '__KEY__': None,
        'WITNESS': '목격',
        '@DT:ONSET_DATE,ONSET_CLOCK_HOUR,ONSET_CLOCK_MIN,ONSET_DATE_UK': '2026-06-15 09:30',
        'WIT_PERSON': '근무중구급대원',
        'WIT_PERSON_ETC': None,
        'ONSET_LOC': '집/거주시설',
        'ONSET_LOC_ETC': None,
        'BYCPR': None,
        '@TREE:BYDEFIB|1=BYDEFIB_Y': None,
        'FIRST_ECG': 'VF',
        'WIT_SEX': '남성',
    },
    '구급단계': {
        '__KEY__': None,
        '@VUK:DISASTER_NUM,DISASTER_NUM_UK,미상': 'Z11111111111',
        '@DT:CALL_DATE,CALL_HOUR,CALL_MIN,CALL_UK': '2026-06-15 09:30',
        '@DT:SCENE_DATE,SCENE_HOUR,SCENE_MIN,SCENE_UK': '2026-06-15 09:30',
        '@DT:DEPARTURE_DATE,DEPARTURE_HOUR,DEPARTURE_MIN,DEPARTURE_UK': '2026-06-15 09:30',
        'MULTI_MOVE': '단일출동',
        'PRE_ECG': '감시하지 않음',
        'PRE_ECG_RH': 'VF',
        'PRE_ECG_RH_ETC': None,
        '@DT:PRE_CPR_START_DATE,PRE_CPR_START_HOUR,PRE_CPR_START_MIN,PRE_CPR_START_UK': '2026-06-15 09:30',
        '@DT:PRE_CPR_STOP_DATE,PRE_CPR_STOP_HOUR,PRE_CPR_STOP_MIN,PRE_CPR_STOP_UK': '2026-06-15 09:30',
        '@VUK:PRE_DEFIB_N,PRE_DEFIB_N_UK,미상': None,
        'PRE_DEFIB': '시행',
        '@DT:PRE_DEFIB_DATE,PRE_DEFIB_HOUR,PRE_DEFIB_MIN,PRE_DEFIB_DATE_UK': '2026-06-15 09:30',
        'PRE_MECHCPR': '적용',
        '@DT:PRE_MECHCPR_DATE,PRE_MECHCPR_HOUR,PRE_MECHCPR_MIN': '2026-06-15 09:30',
        'PRE_ROSC': '회복',
        '@DT:PRE_ROSC_DATE,PRE_ROSC_HOUR,PRE_ROSC_MIN,PRE_ROSC_DATE_UK': '2026-06-15 09:30',
        'FREE_AIRWAY': '확보함',
        '@GROUP:FREE_AIRWAY_OPA,FREE_AIRWAY_SUPR,FREE_AIRWAY_ENDO,FREE_AIRWAY_SURG': 'OPA',
        'DRUG_USE': '사용함',
        '@GROUP:DRUG_USE_EPI,DRUG_USE_AMI,DRUG_USE_BASO': '에피네프린, 아미오다론',
        'PRE_DRUG_EPI_TOT': 5,
        'PRE_DRUG_AMIO_TOT': None,
        'PRE_DRUG_VASO_TOT': None,
    },
    '병원단계': {
        '__KEY__': None,
        'PRE_ROSC': None,
        '@DT:PRE_ROSC_DATE,PRE_ROSC_CLOCK_HOUR,PRE_ROSC_CLOCK_MIN,PRE_ROSC_DATE_UK': None,
        'HOSP_ECG': '심정지리듬',
        'HOSP_ECG_RH': 'VF',
        'EPINE_TOT': 5,
        'EPINE_ROSC': 0,
        '@GROUP:EPINE_UK,EPINE_ND': None,
        '@VUK:DEFIB_CNT,DEFIB_UK,미상': 0,
        'ENDO_INTU': '등록병원 시행',
        'F_AD_AIRWAYD': 'E-tube',
        'F_AD_AIRWAY_ETC': None,
        'F_IV_KIND': 'IV',
        'F_IV_KIND_ETC': None,
        'MECH_CPR': '시행',
        'ETCO2': '시행',
        '@VUK:WBC,WBC_YN,ND': 'ND',
        '@VUK:HB,HB_YN,ND': 'ND',
        '@VUK:PLT,PLT_YN,ND': 'ND',
        '@VUK:CR,CR_YN,ND': 'ND',
        '@VUK:MCH,MCH_YN,ND': 'ND',
        '@VUK:MCV,MCV_YN,ND': 'ND',
        '@VUK:MCHC,MCHC_YN,ND': 'ND',
        '@VUK:RDW,RDW_YN,ND': 'ND',
        '@VUK:NA,NA_YN,ND': 'ND',
        '@VUK:K,K_YN,ND': 'ND',
        '@VUK:CL,CL_YN,ND': 'ND',
        '@VUK:BUN,BUN_YN,ND': 'ND',
        '@VUK:GOT,GOT_YN,ND': 'ND',
        '@VUK:GPT,GPT_YN,ND': 'ND',
        '@VUK:BILI,BILI_YN,ND': 'ND',
        '@VUK:CA,CA_YN,ND': 'ND',
        'ICA_UNIT': None,
        '@VUK:ICA,ICA_YN,ND': 'ND',
        'MG_UNIT': 'mEq/L',
        '@VUK:MG,MG_YN,ND': 'ND',
        '@VUK:P,P_YN,ND': 'ND',
        '@VUK:PROT,PROT_YN,ND': 'ND',
        '@VUK:ALB,ALB_YN,ND': 'ND',
        '@VUK:GLU,GLU_YN,ND': 'ND',
        '@VUK:CHOL,CHOL_YN,ND': 'ND',
        'B_EXCESS_UNIT': 'mmol/L',
        '@VUK:B_EXCESS,B_EXCESS_YN,ND': 'ND',
        'PT_UNIT': '%',
        '@VUK:PT,PT_YN,ND': 'ND',
        '@VUK:APTT,APTT_YN,ND': 'ND',
        '@VUK:INR,INR_YN,ND': 'ND',
        '@VUK:PH,PH_YN,ND': 'ND',
        '@VUK:CO2,CO2_YN,ND': 'ND',
        '@VUK:O2,O2_YN,ND': 'ND',
        '@VUK:SAO2,SAO2_YN,ND': 'ND',
        '@VUK:HCO3,HCO3_YN,ND': 'ND',
        'S100_UNIT': '㎍/mL',
        '@VUK:S100,S100_YN,ND': 'ND',
        '@VUK:NSE,NSE_YN,ND': 'ND',
        'DIMER_UNIT': '㎍/mL',
        '@VUK:DIMER,DIMER_YN,ND': 'ND',
        'LACTATE_UNIT': 'mmol/L',
        '@VUK:LACTATE,LACTATE_YN,ND': 'ND',
        '@VUK:TOT_DEFIB,TOT_DEFIB_YN,ND': 'ND',
        '@VUK:VASOP,VASOP_YN,ND': 'ND',
        'BICAR_UNIT': None,
        '@VUK:BICAR,BICAR_YN,ND': 'ND',
        'AMIODA_UNIT': None,
        '@VUK:AMIODA,AMIODA_YN,ND': 'ND',
        'STEROID_KIND': '미시행',
        'STEROID_KIND_ETC': None,
        'STEROID_UNIT': None,
        '@VUK:STEROID,STEROID_YN,ND': None,
        'LIDOCAINE_UNIT': None,
        '@VUK:LIDOCAINE,LIDOCAINE_YN,ND': 'ND',
        'CA_GLU_UNIT': None,
        '@VUK:CA_GLU,CA_GLU_YN,ND': 'ND',
        '@VUK:CACL_TOT,CACL_TOT_YN,ND': 'ND',
        'EX_CIRC_EXE': '미시행',
        'EX_CIRC_REQ': '요청하지않음',
        'EX_CIR': '미시행',
        '@DT:EX_CIR_S_DATE,EX_CIR_S_HOUR,EX_CIR_S_MIN,EX_CIR_S_DATE_UK': None,
        '@DT:EX_CIR_E_DATE,EX_CIR_E_HOUR,EX_CIR_E_MIN,EX_CIR_E_DATE_UK': None,
        '@DT:ECMO_DATE,ECMO_HOUR,ECMO_MIN,ECMO_DATE_UK': None,
        '@DT:ECMO5_POFF_DATE,ECMO5_POFF_HOUR,ECMO5_POFF_MIN,ECMO5_POFF_UK': None,
        'EX_CIR_SUCC': None,
        '@VUK:ROSC_ALBUMIN,ROSC_ALBUMIN_YN,ND': 'ND',
        'ROSC_12ECG': '미시행',
        'ROSC_12ECG_ETC': None,
        '@VUK:ANO_BODY_TEMP,ANO_BODY_TEMP_YN,ND': 'ND',
        'CPR_COLD_SALINE': '미시행',
    },
    '소생후단계': {
        '__KEY__': None,
        '@VUK:ROSC_SBP,ROSC_SBP_YN,ND': None,
        '@VUK:ROSC_DBP,ROSC_DBP_YN,ND': None,
        '@VUK:ROSC_PR,ROSC_PR_YN,ND': None,
        'HYPER': 'ROSC 24시간 이내',
        '@GROUP:ROSC_INOTR_TYPE1,ROSC_INOTR_TYPE2,ROSC_INOTR_TYPE3,ROSC_INOTR_TYPE4,ROSC_INOTR_TYPE5,ROSC_INOTR_TYPE88,ROSC_INOTR_TYPE99': 'Dopamine',
        'ROSC_INOTR_TYPE_ETC': None,
        'REPER': '등록병원시행',
        'REPER_TIME': '소생술동안',
        'CLOT': '등록병원 시행',
        '@DT:CLOT_DATE,CLOT_HOUR,CLOT_MIN,CLOT_DATE_UK': '2026-06-15 09:30',
        'ANGIO': '등록병원 시행',
        '@DT:ANGIO_DATE,ANGIO_HOUR,ANGIO_MIN,ANGIO_DATE_UK': '2026-06-15 09:30',
        'CA': '등록병원 시행',
        '@DT:CA_DATE,CA_HOUR,CA_MIN,CA_DATE_UK': '2026-06-15 09:30',
        'CAB': '등록병원 시행',
        '@DT:CAB_DATE,CAB_HOUR,CAB_MIN,CAB_DATE_UK': '2026-06-15 09:30',
        'IN_PACEMAKER': '등록병원 시행',
        'IN_DEFIBR': '등록병원 시행',
        '@VUK:RE_FIRST_PH,RE_FIRST_PH_YN,ND': None,
        '@VUK:RE_FIRST_LACTATE,RE_FIRST_LACTATE_YN,ND': None,
        'LAW_TEMP': '시행',
        'EX_LAW_TEMP1': '등록병원 시행',
        'EX_LAW_TEMP2': '등록병원 시행',
        'EX_LAW_TEMP3': '등록병원 시행',
        'IN_LAW_TEMP': '등록병원 시행',
        '@DT:LAW_TEMP_DATE,LAW_TEMP_HOUR,LAW_TEMP_MIN,LAW_TEMP_DATE_UK': '2026-06-15 09:30',
        '@DT:RE_TEMP_DATE,RE_TEMP_HOUR,RE_TEMP_MIN,RE_TEMP_DATE_UK': '2026-06-15 09:30',
        'LAW_TEMP_TARGET': '32-34도',
        'LAW_TEMP_TARGET_ETC': None,
        'RE_TEMP_SPEED': '0.25도/hr',
        'RE_TEMP_SPEED_ETC': None,
        'ECMO7': '시행함',
        '@DT:ECMO7_DATE,ECMO7_HOUR,ECMO7_MIN,ECMO7_DATE_UK': '2026-06-15 09:30',
        'SSEP': '시행함',
        '@DT:SSEP_DATE1,SSEP_HOUR1,SSEP_MIN1,SSEP_DATE_UK1': '2026-06-15 09:30',
        'SSEP_RESULT_CMMT': None,
        'EEG': '시행함',
        '@DT:EEG_DATE1,EEG_HOUR1,EEG_MIN1,EEG_DATE_UK1': '2026-06-15 09:30',
        'EEG_RESULT_CMMT': None,
        'BCT': '시행함',
        '@DT:BCT_DATE,BCT_HOUR,BCT_MIN,BCT_DATE_UK': '2026-06-15 09:30',
        'BCT_RESULT_CMMT': None,
        'BMRI': '시행함',
        '@DT:BMRI_DATE,BMRI_HOUR,BMRI_MIN,BMRI_DATE_UK': '2026-06-15 09:30',
        'BMRI_RESULT_CMMT': None,
        'GCS': '시행함',
        'GCS_E_RESULT': None,
        'GCS_V_RESULT': None,
        'GCS_M_RESULT': None,
        'PLR': '시행함',
        'PLR_RESULT': '유',
        'CR': '시행함',
        'CR_RESULT': '유',
        'SR': '시행함',
        'SR_RESULT': '유',
        'GCS72': '시행함',
        'GCS72_E_RESULT': None,
        'GCS72_V_RESULT': None,
        'GCS72_M_RESULT': None,
        'PLR72': '시행함',
        'PLR72_RESULT': '유',
        'CR72': '시행함',
        'CR72_RESULT': '유',
        'SR72': '시행함',
        'SR72_RESULT': '유',
    },
    '심장검사': {
        '__KEY__': None,
        '@VUK:CKMB,CKMB_YN,ND': 'ND',
        'CKMB_UNIT': None,
        '@DT:CKMB_DATE,CKMB_HOUR,CKMB_MIN,CKMB_DATE_UK': None,
        '@VUK:CKMB_PEAK,CKMB_PEAK_YN,ND': 'ND',
        'CKMB_PEAK_UNIT': None,
        '@DT:CKMB_PEAK_DATE,CKMB_PEAK_HOUR,CKMB_PEAK_MIN,CKMB_PEAK_DATE_UK': None,
        '@VUK:TROP_I,TROP_I_YN,ND': 'ND',
        'TROP_I_UNIT': None,
        '@DT:TROP_I_DATE,TROP_I_HOUR,TROP_I_MIN,TROP_I_DATE_UK': None,
        '@VUK:TROP_I_PEAK,TROP_I_PEAK_YN,ND': 'ND',
        'TROP_I_PEAK_UNIT': None,
        '@DT:TROP_I_PEAK_DATE,TROP_I_PEAK_HOUR,TROP_I_PEAK_MIN,TROP_I_PEAK_DATE_UK': None,
        '@VUK:TROP_T,TROP_T_YN,ND': 'ND',
        'TROP_T_UNIT': None,
        '@DT:TROP_T_DATE,TROP_T_HOUR,TROP_T_MIN,TROP_T_DATE_UK': None,
        '@VUK:TROP_T_PEAK,TROP_T_PEAK_YN,ND': 'ND',
        'TROP_T_PEAK_UNIT': None,
        '@DT:TROP_T_PEAK_DATE,TROP_T_PEAK_HOUR,TROP_T_PEAK_MIN,TROP_T_PEAK_DATE_UK': None,
        '@VUK:BNP,BNP_YN,ND': 'ND',
        'BNP_UNIT': None,
        '@VUK:NTPRO_BNP,NTPRO_BNP_YN,ND': 'ND',
        'NTPRO_BNP_UNIT': None,
        'ECG_DONE1': '미시행',
        'ECHO_DONE1': '미시행',
        'RWMA1': None,
        'CAG_DONE1': '미시행',
        '@TREE:CAG_RE1|3=CAG_RE_SS1;4=CAG_RE_VASOS1': None,
        'CAG_RE_ETC1': None,
        'CAG_DONE2': '미시행',
        '@TREE:CAG_RE2|3=CAG_RE_SS2;4=CAG_RE_VASOS2': None,
        'CAG_RE_ETC2': None,
        'CAG_DONE3': '미시행',
        '@TREE:CAG_RE3|3=CAG_RE_SS3;4=CAG_RE_VASOS3': None,
        'CAG_RE_ETC3': None,
    },
    '소아소생술': {
        '__KEY__': None,
        '@VUK:Y_HEIGHT,Y_HEIGHT_UK,미상': None,
        '@VUK:Y_WEIGHT,Y_WEIGHT_UK,미상': None,
        'Y_INSU': None,
        'EM_TRANS': '예',
        'CPR': '소아응급실',
        'IN_HOSP_ICU': '소아중환자실',
        '@TREE:ARREST_CA|1=ARREST_CA_MEDI;6=ARREST_CA_ASPH': None,
        'Y_ER_HOSP_NM': None,
        'Y_OUT_PCPC': 'PCPC 1 (뇌기능정상)',
        'Y_6M_PCPC': 'PCPC 1 (뇌기능정상)',
        'Y_12M_LIVE': '생존',
        'Y_12M_PCPC': 'PCPC 1 (뇌기능정상)',
        '@DT:Y_DEATH_DATE,Y_DEATH_HOUR,Y_DEATH_MIN,Y_DEATH_DATE_UK': '2026-06-15 09:30',
        'Y_PRE_BABY': '예',
        'BIRTH_ICU': '예',
        'INDEPEND': '예',
        'MEDI_HIST': '없음',
        'MEDI_HIST_ETC': None,
        'Y_BASE_PCPC': 'PCPC 1 (뇌기능정상)',
    },
}
